
<div class="row">
    <div class="col-md-12">
        <h3>Add Snippet</h3>

        <form action="/add" method="post">
            <div class="inputs">
                <h4>Title</h4>
                <input type="text" name="title" class="form-control" placeholder="Snippet title">

                <h4>Text</h4>
                <textarea name="body" class="form-control" placeholder="Snippet body"></textarea>

                <h4>Tags</h4>
                <input type="text" name="tags" class="form-control" placeholder="Set a few tags">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
</div>