
<div class="row" ng-controller="editSnippet">
    <div class="col-md-12">
        <h3>Add Snippet</h3>

        <form action="/add" method="post">
            <div class="inputs">
                <h4>Title</h4>
                <input type="text" name="title" class="form-control" placeholder="Snippet title" required="required">

                <h4>Text</h4>
                <textarea name="body" class="form-control" placeholder="Snippet body" required="required"></textarea>

                <h4>Tags</h4>
                <div tags="tags" new-tag="newTag" rmfn="deleteTag(tag)"></div>
                <input type="text" ng-model="newTag" class="form-control" placeholder="Set a few tags">
                <input type="hidden" name="tags" value="{{tags.join(',')}}"/>
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
</div>