<div class="row">
    <div class="col-md-12">
        <form action="/user/profile" method="post">
<!--            <div class="form-group">-->
<!--                <label for="inputEmail" class="col-lg-2 control-label">Email</label>-->
<!--                <div class="col-lg-10">-->
<!--                    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Type your email" required value="--><?//=$user->email;?><!--">-->
<!--                </div>-->
<!--            </div>-->
            <div class="form-group">
                <label for="inputName" class="col-lg-2 control-label">Name</label>
                <div class="col-lg-10">
                    <input type="text" name="name" id="inputName" class="form-control" placeholder="Type your name" required value="<?=$user->name;?>">
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-10 col-offset-2">
        <a class="btn btn-primary" href="/user/logout">Logout</a>
    </div>
</div>