<!DOCTYPE html>
<html ng-app="Snippets">
	<head>
		<title>Snippets Storage</title>
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.2/css/material.min.css"/>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.2/css/material-wfont.min.css"/>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.2/css/ripples.min.css"/>
		<link href="//cdn.rawgit.com/FezVrasta/dropdown.js/master/jquery.dropdown.css" rel="stylesheet">
		<link rel="stylesheet" href="/css/main.css"/>
	</head>
	<body>

		<div class="navbar navbar-default">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Home</a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="/add">+ Add snippet</a></li>
					<li><a href="/user/auth">
							<i class="mdi-action-account-circle"></i>
							<?=($User->_id ? $User->email : 'Login');?>
						</a></li>
				</ul>
			</div>
		</div>

		<div class="container-fluid">
			<?php echo $this->getContent(); ?>
		</div>

		<footer>
			&copy; 2015 Dniwe's children, faithful sons
		</footer>

		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.2/js/material.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.2/js/ripples.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/noUiSlider/6.2.0/jquery.nouislider.min.js"></script>
		<script src="https://cdn.rawgit.com/FezVrasta/dropdown.js/master/jquery.dropdown.js"></script>
		<script src="//code.angularjs.org/1.2.9/angular.min.js" type="text/javascript"></script>
		<script src="//code.angularjs.org/1.2.9/angular-cookies.min.js" type="text/javascript"></script>
		<script src="/js/app.js" type="text/javascript"></script>
	</body>
</html>